/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Frame: typeof import('./src/components/Frame.vue')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    Prikbord: typeof import('./src/components/Prikbord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
