/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Frame: typeof import('./src/components/Frame.vue')['default']
    IceBox: typeof import('./src/components/iceBox.vue')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    NextPage: typeof import('./src/components/nextPage.vue')['default']
    Nudge: typeof import('./src/components/Nudge.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    Page3A: typeof import('./src/components/frames/Chapter1/Page3A.vue')['default']
    Page3B: typeof import('./src/components/frames/Chapter1/Page3B.vue')['default']
    ParticleContainer: typeof import('./src/components/ParticleContainer.vue')['default']
    Prikbord: typeof import('./src/components/Prikbord.vue')['default']
    PrikbordItem: typeof import('./src/components/PrikbordItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
